# Generated by Django 3.1.1 on 2020-09-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaltv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_models',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
