# Generated by Django 3.1.1 on 2020-09-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaltv_app', '0004_remove_post_models_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_pageCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviePgaecover', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='youtube_videoplaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=255)),
                ('playlist_code', models.CharField(max_length=800)),
            ],
        ),
        migrations.RemoveField(
            model_name='post_models',
            name='catgory',
        ),
        migrations.AddField(
            model_name='post_models',
            name='catgory',
            field=models.ManyToManyField(blank=True, to='roaltv_app.catgory_list'),
        ),
    ]
