# Generated by Django 3.1.1 on 2020-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaltv_app', '0006_livetvlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_videoplaylist',
            name='channel_id',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
    ]
