# Generated by Django 3.1.1 on 2020-10-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaltv_app', '0008_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='admove_ad_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_code', models.TextField(blank=True)),
            ],
        ),
    ]
