# Generated by Django 3.1.1 on 2020-10-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roaltv_app', '0009_admove_ad_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='catgory_list',
            options={'verbose_name': 'Create Category', 'verbose_name_plural': 'Create Category'},
        ),
        migrations.AlterModelOptions(
            name='livetvlink',
            options={'verbose_name': 'Live Tv Url', 'verbose_name_plural': 'Live Tv Url'},
        ),
        migrations.AlterModelOptions(
            name='movie_pagecover',
            options={'verbose_name': 'Cover Img', 'verbose_name_plural': 'Cover Img'},
        ),
        migrations.AlterModelOptions(
            name='post_models',
            options={'verbose_name': 'Post News', 'verbose_name_plural': 'Post News'},
        ),
        migrations.AlterModelOptions(
            name='youtube_videoplaylist',
            options={'verbose_name': 'Create YouTube PlayList', 'verbose_name_plural': 'Create YouTube PlayList'},
        ),
    ]
