# Generated by Django 3.1.1 on 2020-10-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roaltv_app', '0012_auto_20201013_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps_coverimg',
            old_name='howpage',
            new_name='typeimg',
        ),
    ]
