# Generated by Django 2.2.5 on 2020-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaltv_app', '0014_auto_20201013_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='livetvlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channe_name', models.CharField(max_length=100)),
                ('channel_logo', models.URLField(max_length=400)),
                ('channel_tvurl', models.URLField(max_length=400)),
                ('release_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
