# Generated by Django 2.2.5 on 2020-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaltv_app', '0015_livetvlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='liveweblisttvlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_logo', models.URLField(max_length=400)),
                ('web_link', models.URLField(max_length=400)),
                ('release_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
