# Generated by Django 2.2.5 on 2020-10-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaltv_app', '0018_auto_20201016_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_atn',
            options={'verbose_name': 'Apps About', 'verbose_name_plural': 'Apps About'},
        ),
        migrations.AlterModelOptions(
            name='admove_ad_code',
            options={'verbose_name': 'AdMob', 'verbose_name_plural': 'AdMob'},
        ),
        migrations.AlterModelOptions(
            name='apps_coverimg',
            options={'verbose_name': 'cover img', 'verbose_name_plural': 'cover img'},
        ),
        migrations.AlterModelOptions(
            name='livetvlist',
            options={'verbose_name': 'Create livetv', 'verbose_name_plural': 'Create livetv'},
        ),
        migrations.AlterModelOptions(
            name='liveweblisttvlist',
            options={'verbose_name': 'Create Weblist', 'verbose_name_plural': 'Create Weblist'},
        ),
        migrations.AlterField(
            model_name='admove_ad_code',
            name='ads_page',
            field=models.CharField(blank=True, choices=[('home_page_banner_ad', 'home_page_banner_ad'), ('youtube_page', 'youtube_page'), ('home_page_bottom_ads', 'global_bottom_page_ads'), ('home_page_bottom_ads', 'home_web_tabs_ads'), ('home_page_bottom_ads', 'home_youtube_tabs_ads')], default='home_page_banner_ad', max_length=200),
        ),
    ]
